[workspace]
members = [
  "./common",
  "./device",
  "./download",
  "./driver",
  "./enumeration",
  "./sdk",
  "./streaming",
  "./sys",
]
resolver = "2"

[profile.release]
# codegen-units = 1
debug = true
debuginfo = 2
lto = true
split-debuginfo = "packed"
strip = true
